---
- hosts: localhost
  become: yes
  tasks:
    - name: Atualizar pacotes apt
      apt:
        update_cache: yes
        force_apt_get: yes

    - name: Instalar Apache
      apt:
        name: apache2
        state: present

    - name: Instalar PHP e módulos necessários
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - php
        - libapache2-mod-php

    - name: Reiniciar o Apache para carregar o PHP
      systemd:
        name: apache2
        state: restarted

    - name: Criar diretório da aplicação PHP
      file:
        path: /var/www/html/minha_aplicacao
        state: directory
        mode: '0755'

    - name: Copiar o arquivo index.php para o diretório da aplicação
      copy:
        src: ./index.php
        dest: /var/www/html/minha_aplicacao/index.php
        mode: '0644'

    - name: Reiniciar Apache após copiar a aplicação
      systemd:
        name: apache2
        state: restarted
